[general]
import = [ "~/.config/alacritty/dank-theme.toml" ]

[font.normal]
family = "Miracode"

[colors]
transparent_background_colors = true

[cursor.style]
shape = "Beam"

[cursor.vi_mode_style]
shape = "Block"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t¦┆┆%"

[terminal.shell]
program = "fish"
args = ["--login"]

[window]
dynamic_padding = true
opacity = 0.95

[window.padding]
x = 6
y = 6
