[colors.primary]
background = '#10150a'
foreground = '#dfe5d2'

[colors.selection]
text = '#dfe5d2'
background = '#5e4200'

[colors.cursor]
text = '#10150a'
cursor = '#f7bd48'

[colors.normal]
black   = '#10150a'
red     = '#e2497b'
green   = '#95d66e'
yellow  = '#dbaf7b'
blue    = '#b68524'
magenta = '#b99650'
cyan    = '#f7bd48'
white   = '#abb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#e05f8c'
green   = '#a7e086'
yellow  = '#e8c397'
blue    = '#f8ce8a'
magenta = '#a46c39'
cyan    = '#8a7938'
white   = '#ffffff'
