[colors.primary]
background = '#141316'
foreground = '#e6e1e5'

[colors.selection]
text = '#e6e1e5'
background = '#3f335e'

[colors.cursor]
text = '#141316'
cursor = '#cebff3'

[colors.normal]
black   = '#141316'
red     = '#e15242'
green   = '#6ed675'
yellow  = '#dbd97b'
blue    = '#926dde'
magenta = '#a097b6'
cyan    = '#cebff3'
white   = '#abb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#e06a5f'
green   = '#86e08b'
yellow  = '#e8e697'
blue    = '#dcccff'
magenta = '#7c6bc9'
cyan    = '#8a6bb2'
white   = '#ffffff'
