[colors.primary]
background = '#0b160f'
foreground = '#d9e6da'

[colors.selection]
text = '#d9e6da'
background = '#4a4900'

[colors.cursor]
text = '#0b160f'
cursor = '#cdcc56'

[colors.normal]
black   = '#0b160f'
red     = '#e34a75'
green   = '#91d66e'
yellow  = '#dbb37b'
blue    = '#96961e'
magenta = '#999952'
cyan    = '#cdcc56'
white   = '#abb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#e05f87'
green   = '#a4e086'
yellow  = '#e8c797'
blue    = '#dcd88a'
magenta = '#8a7932'
cyan    = '#777e3b'
white   = '#ffffff'
