[colors.primary]
background = '#121317'
foreground = '#e3e2e8'

[colors.selection]
text = '#e3e2e8'
background = '#7593d4'

[colors.cursor]
text = '#121317'
cursor = '#aec6ff'

[colors.normal]
black   = '#121317'
red     = '#e54d45'
green   = '#6fd66e'
yellow  = '#dbd27b'
blue    = '#617fd1'
magenta = '#8e9dbf'
cyan    = '#aec6ff'
white   = '#abb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#e0615f'
green   = '#86e086'
yellow  = '#e8e197'
blue    = '#bad4ff'
magenta = '#537cae'
cyan    = '#6c75b4'
white   = '#ffffff'
