[colors.primary]
background = '#151310'
foreground = '#e7e2dc'

[colors.selection]
text = '#e7e2dc'
background = '#9d9062'

[colors.cursor]
text = '#151310'
cursor = '#d5c693'

[colors.normal]
black   = '#151310'
red     = '#e14878'
green   = '#93d66e'
yellow  = '#dbb17b'
blue    = '#9c863e'
magenta = '#9f9678'
cyan    = '#d5c693'
white   = '#abb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#e05f8b'
green   = '#a6e086'
yellow  = '#e8c497'
blue    = '#e4d49d'
magenta = '#957345'
cyan    = '#807a44'
white   = '#ffffff'
